import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("./TimeSeries/time_seriesInelastic_pt2.csv")

#plt.figure(figsize=(20,10))
#plt.subplot(4,1,1)
plt.plot(df["cubeJuliaTimeStep"], df[" GesamtImpluls"])
plt.ylabel("[p] = Ns")
plt.xlabel("[t] = s")
plt.xlim(0,19)
plt.ylim(-0.5,5)
plt.title("Gesamtimpuls als Funktion der Zeit")
plt.savefig('../Semesterprojekt Physik Engines/images/Inelastisch/GesamtImpluls.png', dpi=300, bbox_inches='tight')
plt.show()

#plt.figure(figsize=(20,20))
#plt.subplot(4,1,1)
plt.plot(df["cubeJuliaTimeStep"], df[" cubeRomeoImpulse"], label="Romeo")
plt.plot(df["cubeJuliaTimeStep"], df[" cubeJuliaImpulse"], label="Julia")
plt.ylabel("[p] = Ns")
plt.xlabel("[t] = s")
plt.xlim(0,19)
plt.ylim(-0.5,5)
plt.legend()
plt.title("Impuls Romeo & Julia als Funktion der Zeit")
plt.savefig('../Semesterprojekt Physik Engines/images/Inelastisch/ImpulsRomeoJulia.png', dpi=300, bbox_inches='tight')
plt.show()

#plt.figure(figsize=(20,20))
#plt.subplot(4,1,1)
plt.plot(df["cubeJuliaTimeStep"], df[" cubeRomeo.position.x"], label="Romeo")
plt.plot(df["cubeJuliaTimeStep"], df[" cubeJulia.position.x"], label="Julia")
plt.ylabel("[s] = m")
plt.xlabel("[t] = s")
plt.xlim(0,19)
plt.ylim(-15,10)
plt.legend()
plt.title("Ort Romeo & Julia als Funktion der Zeit")
plt.savefig('../Semesterprojekt Physik Engines/images/Inelastisch/OrtRomeoJuliaAlsFunktionDerZeit.png', dpi=300, bbox_inches='tight')
plt.show()

#plt.subplot(4,1,2)
plt.plot(df["cubeJuliaTimeStep"], df[" cubeRomeo.velocity.x"], label="Romeo")
plt.plot(df["cubeJuliaTimeStep"], df[" cubeJulia.velocity.x"], label="Julia")
plt.ylabel("[v] = m/s")
plt.xlabel("[t] = s")
plt.xlim(0,19)
plt.ylim(-2.5,2.5)
plt.legend()
plt.title("Geschwindigkeit Romeo & Julia als Funktion der Zeit")
plt.savefig('../Semesterprojekt Physik Engines/images/Inelastisch/GeschwindigkeitRomeoJulia.png', dpi=300, bbox_inches='tight')
plt.show()


#plt.subplot(4,1,2)
plt.plot(df["cubeJuliaTimeStep"], df[" velocityEnd"])
plt.ylabel("[v] = m/s")
plt.xlabel("[t] = s")
plt.xlim(0,19)
plt.ylim(-0.1,1.2)
plt.title("Endgeschwindigkeit als Funktion der Zeit")
plt.savefig('../Semesterprojekt Physik Engines/images/Inelastisch/Endgeschwindigkeit.png', dpi=300, bbox_inches='tight')
plt.show()

#%%
#plt.subplot(4,1,2)
plt.plot(df["cubeJuliaTimeStep"], df[" cubeRomeo.velocity.x"])
plt.ylabel("[v] = m/s")
plt.xlabel("[t] = s")
plt.xlim(0,20)
plt.title("Geschwindigkeit Romeo als Funktion der Zeit")
plt.savefig('../Semesterprojekt Physik Engines/images/Inelastisch/GeschwindigkeitRomeo.png', dpi=300, bbox_inches='tight')
plt.show()

#plt.subplot(4,1,3)
plt.plot(df["cubeJuliaTimeStep"], df[" cubeJulia.velocity.x"])
plt.ylabel("[v] = m/s")
plt.xlabel("[t] = s")
plt.xlim(0,20)
plt.title("Geschwindigkeit Julia als Funktion der Zeit")
plt.savefig('../Semesterprojekt Physik Engines/images/Inelastisch/GeschwindigkeitJulia.png', dpi=300, bbox_inches='tight')
plt.show()


plt.subplot(4,1,4)
plt.plot(df["cubeJuliaTimeStep"], df[" cubeRomeoKinetic"])
plt.ylabel("[J] = Nm")
plt.xlabel("[t] = s")
plt.title("Energie Romeo als Funktion der Zeit")
plt.show()

plt.subplot(4,1,3)
plt.plot(df["cubeJuliaTimeStep"], df[" cubeKineticEnd"])
plt.ylabel("[J] = Nm")
plt.xlabel("[t] = s")
plt.title("Endkinetik als Funktion der Zeit")
plt.show()
plt.savefig('../Semesterprojekt Physik Engines/images/Inelastisch/cubeKineticEnd.png', dpi=300, bbox_inches='tight')

plt.subplot(4,1,4)
plt.plot(df["cubeJuliaTimeStep"], df[" forceOnJulia"])
plt.ylabel("N")
plt.xlabel("[t] = s")
plt.title("Kraft auf Julia als Funktion der Zeit")
plt.savefig('../Semesterprojekt Physik Engines/images/Inelastisch/forceOnJulia.png', dpi=300, bbox_inches='tight')
